// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/superjcd/userservice/config"
	"github.com/superjcd/userservice/genproto/v1"
	"github.com/superjcd/userservice/service"
)

// Injectors from wire.go:

// InitServer Inject service's component
func InitServer(conf *config.Config) (v1.UserServiceServer, error) {
	userServiceClient, err := service.NewClient(conf)
	if err != nil {
		return nil, err
	}
	userServiceServer, err := service.NewServer(conf, userServiceClient)
	if err != nil {
		return nil, err
	}
	return userServiceServer, nil
}
